const GET_PAGES = "GET_PAGES";
const GET_INPUT = "GET_INPUT";
const GET_BY_ID = "GET_BY_ID";
const GET_BY_NAME = "GET_BY_NAME";
const HANDLE_INPUT = "HANDLE_INPUT";
const INPUT_RESET = "INPUT_RESET";
const PAGE_VALUE_RESET = "PAGE_VALUE_RESET";
const PAGE_VALUE_HANDLER = "PAGE_VALUE_HANDLER";


export {
    GET_PAGES,
    GET_INPUT,
    GET_BY_ID,
    GET_BY_NAME,
    HANDLE_INPUT,
    INPUT_RESET,
    PAGE_VALUE_RESET,
    PAGE_VALUE_HANDLER
};